{{- if .Values.dockerconfigjson }}
---
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.dockerconfigjson | b64enc }}
kind: Secret
metadata:
  name: registrysecret
type: kubernetes.io/dockerconfigjson
{{- end }}
