version: "3.3"
services:
  app:
    environment:
      - "SQLITE_FILE=/app/app.db"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["tail","-f", "/dev/null"]
    image: $WERF_BASICAPP_DOCKER_IMAGE_NAME
